FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy and build everything else
COPY . ./
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/sunrise-alarm.dll"]